### ISSUE TITLE
Option to run version check on any command

### ISSUE THREAD

**Issue by janslow** [babylonhealth/shipcat#263]
Currently, the Shipcat version check (i.e., is your Shipcat out of date) is only used on certain commands or when Shipcat fails to parse `shipcat.conf`.

This means some Shipcat commands will just produce incorrect output when Shipcat is too old, rather than telling the user to update Shipcat.

We should make the `--skip-version-check` flag global (it's currently only available on `shipcat validate`) and then always check the version in `Config.read_from` (unless the version check is explicitly skipped).

**Comment by clux** [comment]
I think this is fine to do. I'd rather be in favour of a `--strict-version-check` flag that we put in all automation in manifests. Currently, this is a nice way to allow people to `shipcat login` without it being problematic.

**Comment by janslow** [comment]
Makes sense

**Comment by clux** [comment]
Then this is easy.

- add a new global flag (ala verbose): --strict-version-check`
- run config verify with version check when fetching the config if the flag is set

**Comment by janslow** [comment]
It'd be useful to log a warning if the version is out of date, even if the check isn't set.

Therefore, if something behaves weirdly (e.g., during `shipcat login`), it at least suggests a fix.
