### ISSUE TITLE
swap over from openssl to rustls

### ISSUE THREAD

**Issue by clux** [babylonhealth/shipcat#329]
For various reasons:

- version pinning on macos can break autoupgrade
- rustls can compile statically without my hacky build container
- openssl is shit

**Comment by clux** [comment]
Two main uses of it are reqwest, and kube (via its reqwest dependency). Need to solve https://github.com/clux/kube-rs/issues/66 first.

**Comment by clux** [comment]
This is actually a little more necessary now due to macos being especially annoying with ssl dylibs on catalina :/

**Comment by clux** [comment]
People have been doing this stuff:

```
ln -s /usr/local/opt/openssl/lib/libssl.dylib /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
ln -s /usr/local/opt/openssl/lib/libcrypto.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
```

**Comment by stefanouliari-babylonhealth** [comment]
Compiling Shipcat source code is the probably a less hacky way..

**Comment by clux** [comment]
Managed to get the `kube` library to compile with rustls over the weekend. Need to upgrade shipcat to:

- use kube >= 0.25.0
- support basic async as new `kube` uses async/await (tested a bit in #383 )
- upgrade reqwest elsewhere to 0.10.1

**Comment by clux** [comment]
Need to do #394 first to upgrade to kube 0.25.0

**Comment by clux** [comment]
Need to also do #404 - but that is much easier now that #394 is done.

**Comment by clux** [comment]
From 0.148.0 rustls is used in shipcat_cli, and openssl has been banished from that dependency tree.
