### ISSUE TITLE
Add support for Kubernetes 1.16

### ISSUE THREAD

**Issue by nandaloussiBabylon** [babylonhealth/shipcat#365]
With the newer versions of K8s, some of the API support has changed and no longer supports the Deployment extensions/v1beta1 api. it should be changed to support apps/v1 etc.

users will get the following error messages:

```
kubectl diff stderr: error: unable to recognize "./service-name.shipcat.tpl.gen.yml": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Comment by clux** [comment]
That is a chart feature in your manifests repository. Shipcat currently does not bundle a chart other than the example chart, and that has [already been switched over to use apps/v1](https://github.com/babylonhealth/shipcat/blob/master/examples/charts/base/templates/deployment.yaml#L1-L2).
