### ISSUE TITLE
diff masking of secret could be better

### ISSUE THREAD

**Issue by clux** [babylonhealth/shipcat#438]
We currently mask all secrets found in vault by a literal replace on the diff.

This works, but has 2 negative consequences:

- it reveals people using trivial passwords matching service names (by masking in an expected place)
- it reveals old passwords on changes

The latter is obviously more problematic as people use password generators.

But there is something we could do to improve this:

- [ ] parse the diff output as the corresponding kubernetes objects
- [ ] any diff to the secret objects, replace contents with "+++Secret diff concealed"

This would be analogous to what helm diff does.

**Comment by palfrey** [comment]
Could also look at the diff for the new secrets? Most of the data is of the form `<key>: <value>` and if you have one of those where a `<value>` matches one of the secrets already known, then mask anything else with that `<key>`? I can imagine a few ways to do this with Regex fun.

**Comment by clux** [comment]
Yeah, that might be possible, though my backreference-fu isn't that great. Still all the logic is in here: https://github.com/babylonhealth/shipcat/blob/master/shipcat_cli/src/diff.rs#L219-L283 and generally not too complicated so far. If you have a good idea, go for it !
